# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7d602f72685feb4af295b2fee477ff14248a6d05c86f1085bcb82cfe0afc1c6d354554988d1a4b5ea16af8d13a43460f303874234ffb7714e9ae45a8b2ee9d8

test:
  secret_key_base: 9f60d5910f36510d301c4b73830139ef9272cb4183d7fa27016eb0ca0b6221728d2118dd030d1c1fcc6c2a6f79d86d881c92e6929e7b8b0f786c8e00cc4267ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
